/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-11-15T21:12:04.614312100+01:00[Europe/Prague]")
@Validated
@Api(value = "reserve", description = "the reserve API")
public interface ReserveApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /reserve : Make a reservation
     *
     * @param token Security token (required)
     * @param reservation Flight IDs of flights to reserve (required)
     * @return Reservation is now Pending (status code 201)
     *         or Not logged in (status code 401)
     *         or Invalid input (status code 403)
     *         or Internal server error occured (status code 500)
     */
    @ApiOperation(value = "Make a reservation", nickname = "reserve", notes = "", tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Reservation is now Pending"),
        @ApiResponse(code = 401, message = "Not logged in"),
        @ApiResponse(code = 403, message = "Invalid input"),
        @ApiResponse(code = 500, message = "Internal server error occured") })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/reserve",
        consumes = { "application/json", "application/xml" }
    )
    default ResponseEntity<Void> reserve(@ApiParam(value = "Security token", required = true) @RequestHeader(value = "token", required = true) String token,@ApiParam(value = "Flight IDs of flights to reserve", required = true) @Valid @RequestBody Object reservation) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
